/**
 * ScenarioIllustration - hero scene illustration for scenario cards.
 *
 * Loads a PNG from `/illustrations/{scene}.png` (generated by
 * `scripts/gen_illustrations.py` via DALL-E 3) and lays it out as a
 * full-bleed left column on desktop, stacked banner on mobile.
 *
 * Falls back to a tinted placeholder if the image hasn't been
 * generated yet, so layout is stable in dev before the assets exist.
 *
 * Usage in a card:
 *   <Card>
 *     <div className="flex flex-col md:flex-row">
 *       <ScenarioIllustration scene="stay" color={config.color} />
 *       <div className="flex-1 min-w-0">
 *         <CardHeader>...</CardHeader>
 *         <CardContent>...</CardContent>
 *       </div>
 *     </div>
 *   </Card>
 *
 * @module components/ScenarioIllustration
 */
import { useState } from 'react'
import { cn } from '@/lib/utils'

export type IllustrationScene =
  | 'stay'
  | 'refinance'
  | 'sell_buy'
  | 'rent'
  | 'rent_out_buy'

interface ScenarioIllustrationProps {
  scene: IllustrationScene
  /** Accent color used for the placeholder + a thin top border */
  color?: string
  /** Override default desktop column width (Tailwind w-* class string) */
  widthClass?: string
  className?: string
}

export function ScenarioIllustration({
  scene,
  color = '#94a3b8',
  widthClass = 'md:w-72',
  className,
}: ScenarioIllustrationProps) {
  const [errored, setErrored] = useState(false)

  return (
    <div
      className={cn(
        'relative shrink-0 self-stretch overflow-hidden',
        // mobile: 16:9 banner up top; desktop: full-height left column
        'aspect-[16/9] w-full md:aspect-auto md:h-auto',
        widthClass,
        className,
      )}
      style={{ backgroundColor: `${color}14` }} // 14 = ~8% alpha hex
    >
      {!errored ? (
        <img
          src={`/illustrations/${scene}.png`}
          alt=""
          aria-hidden="true"
          loading="lazy"
          decoding="async"
          onError={() => setErrored(true)}
          className="absolute inset-0 h-full w-full object-cover"
        />
      ) : (
        // Placeholder shown until the PNG is generated. Renders a soft
        // accent gradient so the card still looks intentional.
        <div
          className="absolute inset-0"
          style={{
            background: `linear-gradient(135deg, ${color}33 0%, ${color}11 60%, ${color}05 100%)`,
          }}
          aria-hidden="true"
        />
      )}
    </div>
  )
}
